language: objective-c
osx_image: xcode7.1
xcode_project: SDDKit.xcodeproj
xcode_scheme: SDDKit
sudo: false
env:
  global:
  - LC_CTYPE=en_US.UTF-8
  - LANG=en_US.UTF-8
  - LANGUAGE=en_US.UTF-8
  - FASTLANE_LANE=ci_commit
matrix:
  include:
    - osx_image: xcode8
      env: FASTLANE_LANE=code_coverage FASTLANE_ENV=default
    - osx_image: xcode8
      env: FASTLANE_ENV=ios10_xcode8
    - osx_image: xcode8
      env: FASTLANE_ENV=tvos10_xcode8
    - osx_image: xcode8
      env: FASTLANE_ENV=osx
    - osx_image: xcode7.3
      env: FASTLANE_ENV=ios93_xcode73
    - osx_image: xcode7.3
      env: FASTLANE_ENV=ios81_xcode73
